name: Sonar Cloud - Branch Analysis

on:
  push:
    branches: 
      - main

jobs:
  sonarcloud:
    name: Build (Sonar Cloud)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - uses: actions/setup-node@v3
      with:
        node-version: '18'
      

    - name: Node install dependencies
      run: npm install

    - name: Run unit tests
      run: npm run test

    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@v4.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: -X